{
  "name": "Data center patrolling",

  "duration_minutes": 66,

  "goals": [

    {

      "id": "0",

      "action": "SNAP",

      "position": {

        "x": 0,

        "y": 10

      }

    },

    {

      "id": "1",

      "action": "TEMP",

      "position": {

        "x": 10,

        "y": 10

      }

    },

    {

      "id": "2",

      "action": "TURN",

      "position": {

        "x": 10,

        "y": 20

      }

    }

  ]

}
