{
  "name": "Data center patrolling",

  "duration_minutes": 66,

  "goals": [

    {

      "id": "0",

      "action": "SNAP",

      "position": {

        "x": 3,

        "y": 1

      }

    },

    {

      "id": "1",

      "action": "TEMP",

      "position": {

        "x": 1,

        "y": 2

      }

    },

    {

      "id": "2",

      "action": "TURN",

      "position": {

        "x": 4.4444,

        "y": 0.4444

      }

    }

  ]

}
